---
title: "Sampling from the Main Dataset"
author: "Sai"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Necessary Libraries


```{r,warning=FALSE,message=FALSE}
library(tidyverse)
library(skimr)
```


## Load & Inspect the Dataset

```{r,warning=FALSE,message=FALSE}
crime <- read_csv("./data/crime_sample.csv")
crime
skim(crime)
```
## Do typesetting to the important columns again and inspect.
```{r,warning=FALSE,message=FALSE}
crime <- crime %>%
  mutate(
    highest_offense_description = as.factor(highest_offense_description),
    highest_offense_code           = as.factor(highest_offense_code),
    family_violence                = as.factor(family_violence),
    occurred_date_time_month       = as.ordered(occurred_date_time_month),
    occurred_date_time_day_of_week = as.ordered(occurred_date_time_day_of_week),
    location_type                  = as.factor(location_type),
    apd_sector                     = as.factor(apd_sector),
    apd_district                   = as.factor(apd_district),
    clearance_status               = as.factor(clearance_status)
  )

skim(crime)
```

```{r,warning=FALSE,message=FALSE}
top_codes <- crime %>% count(highest_offense_code, sort=TRUE) %>% slice_head(n=20) %>% pull(highest_offense_code)
crime <- crime %>%
  mutate(
    hoc_binned = ifelse(highest_offense_code %in% top_codes, as.character(highest_offense_code), "Other"),
    hoc_binned = factor(hoc_binned)
  )

# Now stratify by these:
# - hoc_binned (now only 21 levels)
# - occurred_date_time_year (22 levels)
# - family_violence (2 levels)
# - apd_sector (10 levels)

# This makes about 21*22*2*10 = 9,240 strata (very manageable for your data size).

crime_sample_10pct <- crime %>%
  group_by(hoc_binned, occurred_date_time_year, family_violence, apd_sector) %>%
  sample_frac(0.10) %>%
  ungroup() %>%
  mutate(-hoc_binned)
```

```{r,warning=FALSE,message=FALSE}
#write_csv(crime_sample_10pct, "./data/crime_sample_cleaned.csv")
```

```{r,warning=FALSE,message=FALSE}

```


