---
title: "Test_Data_Cleaning"
author: "Sai"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the necessary libraries. 

```{r,warning=FALSE,message=FALSE}
library(tidyverse)
library(skimr)
```

## Load the test data.
```{r,warning=FALSE,message=FALSE}
ctest <- read_csv("./data/crime_test.csv")
ctest
skim(ctest)
```
## Sample only the 10,000 rows of the test dataset.
```{r,warning=FALSE,message=FALSE}
library(tidyverse)
set.seed(1906525)

# Bin highest_offense_code: Top 20 frequent codes, others as "Other"
top_codes <- ctest %>% count(highest_offense_code, sort=TRUE) %>% slice_head(n=20) %>% pull(highest_offense_code)
ctest <- ctest %>%
  mutate(
    hoc_binned = ifelse(highest_offense_code %in% top_codes, as.character(highest_offense_code), "Other"),
    hoc_binned = factor(hoc_binned)
  )

# Now stratify by these:
# - hoc_binned (now only 21 levels)
# - occurred_date_time_year (22 levels)
# - family_violence (2 levels)
# - apd_sector (10 levels)

# This makes about 21*22*2*10 = 9,240 strata (very manageable for your data size).

crime_sample_65pct <- ctest %>%
  group_by(hoc_binned, occurred_date_time_year, family_violence, apd_sector) %>%
  sample_frac(0.65) %>%
  ungroup()

crime_sample_65pct <- crime_sample_65pct %>% mutate(
  hoc_binned = NULL
)

crime_sample_65pct <- crime_sample_65pct %>% mutate(
    highest_offense_description = as.factor(highest_offense_description),
    highest_offense_code           = as.factor(highest_offense_code),
    family_violence                = as.factor(family_violence),
    occurred_date_time_month       = as.ordered(occurred_date_time_month),
    occurred_date_time_day_of_week = as.ordered(occurred_date_time_day_of_week),
    location_type                  = as.factor(location_type),
    apd_sector                     = as.factor(apd_sector),
    apd_district                   = as.factor(apd_district)
  )

# write_csv(crime_sample_65pct, "./data/crime_test_i.csv")
```

```{r,warning=FALSE,message=FALSE}
rm(crime_sample_65pct)
```

```{r,warning=FALSE,message=FALSE}
cti <- read_csv("./data/crime_test_i.csv")
skim(cti)
```
## Do typesetting and extract the useful values from report_date_time column for cyclic encoding with sine/cosine. 

```{r,warning=FALSE,message=FALSE}
rm(ctest)
cti <- cti %>%
  mutate(
    highest_offense_description = as.factor(highest_offense_description),
    highest_offense_code           = as.factor(highest_offense_code),
    family_violence                = as.factor(family_violence),
    occurred_date_time_month       = as.ordered(occurred_date_time_month),
    occurred_date_time_day_of_week = as.ordered(occurred_date_time_day_of_week),
    location_type                  = as.factor(location_type),
    apd_sector                     = as.factor(apd_sector),
    apd_district                   = as.factor(apd_district),
    clearance_status               = as.factor(clearance_status)
  )

skim(cti)
```

```{r,warning=FALSE,message=FALSE}
library(dplyr)
library(lubridate)
library(forcats)

# Define ordered month levels
month_levels <- month.name

# Step 1: Extract all date/time components from report_date_time
ctii <- cti %>%
  mutate(
    # Numeric year
    report_date_time_year = year(report_date_time),
    # Numeric week of year (1-53)
    report_date_time_week_of_year = isoweek(report_date_time),
    # Numeric day of month (1-31)
    report_date_time_day = day(report_date_time),
    # Numeric hour (0-23)
    report_date_time_hour = hour(report_date_time),
    # Numeric minute (0-59)
    report_date_time_minute = minute(report_date_time),
    # Month as ordered factor
    report_date_time_month = factor(month.name[month(report_date_time)],
                                    levels = month_levels, ordered = TRUE),
    # Day of week as ordered factor (Sunday, Monday, ...)
    report_date_time_day_of_week = factor(weekdays(report_date_time),
                                          levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"), ordered = TRUE)
  )

# Step 2: Move new columns directly after report_time
# Find the column position of 'report_time'
pos <- which(names(ctii) == "report_time")

# Names of new columns in desired order
new_cols <- c("report_date_time_year", "report_date_time_week_of_year", "report_date_time_day", "report_date_time_hour",
              "report_date_time_minute", "report_date_time_month", "report_date_time_day_of_week")

# Rearrange columns: all columns up to report_time, then new columns, then rest
ctii <- ctii %>%
  select(
    1:pos,
    all_of(new_cols),
    (pos+1):(ncol(ctii) - length(new_cols))
  )

```

## View the data features.
```{r,warning=FALSE,message=FALSE}
ctii <- ctii %>%
  mutate(
    highest_offense_description = as.factor(highest_offense_description),
    highest_offense_code           = as.factor(highest_offense_code),
    family_violence                = as.factor(family_violence),
    occurred_date_time_month       = as.ordered(occurred_date_time_month),
    occurred_date_time_day_of_week = as.ordered(occurred_date_time_day_of_week),
    location_type                  = as.factor(location_type),
    apd_sector                     = as.factor(apd_sector),
    apd_district                   = as.factor(apd_district),
    clearance_status               = as.factor(clearance_status)
  )

skim(ctii)
```
## Do sine, cosine transformations to cyclic columns of both the occurred and report columns.

```{r,warning=FALSE,message=FALSE}
library(dplyr)
library(tibble)

# Sine/cosine transformation functions
sine_cyc <- function(x, max_val) sin(2 * pi * x / max_val)
cosine_cyc <- function(x, max_val) cos(2 * pi * x / max_val)

# Helper to add features immediately after each variable
add_cyclic_features <- function(df, var, max_val, prefix) {
  col_idx <- which(names(df) == var)
  # Use integer for factors
  if (is.factor(df[[var]])) {
    x_val <- as.integer(df[[var]])
  } else {
    x_val <- df[[var]]
  }
  sin_col <- sine_cyc(x_val, max_val)
  cos_col <- cosine_cyc(x_val, max_val)
  sin_name <- paste0("sine_", prefix)
  cos_name <- paste0("cosine_", prefix)
  add_cols <- tibble(!!sin_name := sin_col, !!cos_name := cos_col)
  df <- add_column(df, !!!add_cols, .after = col_idx)
  df
}

cyclic_vars <- list(
  list(var = "occurred_date_time_month",       max = 12, prefix = "odt_month"),
  list(var = "occurred_date_time_day_of_week", max = 7,  prefix = "odt_day_of_week"),
  list(var = "report_date_time_month",         max = 12, prefix = "rdt_month"),
  list(var = "report_date_time_day_of_week",   max = 7,  prefix = "rdt_day_of_week"),
  list(var = "occurred_date_time_week_of_year",max = 53, prefix = "odt_week_of_year"),
  list(var = "occurred_date_time_day",         max = 31, prefix = "odt_day"),
  list(var = "occurred_date_time_hour",        max = 24, prefix = "odt_hour"),
  list(var = "occurred_date_time_minute",      max = 60, prefix = "odt_minute"),
  list(var = "report_date_time_week_of_year",  max = 53, prefix = "rdt_week_of_year"),
  list(var = "report_date_time_day",           max = 31, prefix = "rdt_day"),
  list(var = "report_date_time_hour",          max = 24, prefix = "rdt_hour"),
  list(var = "report_date_time_minute",        max = 60, prefix = "rdt_minute")
)

# Start from ctii and assign to ctiii
ctiii <- ctii
for (item in cyclic_vars) {
  ctiii <- add_cyclic_features(
    ctiii, 
    var = item$var, 
    max_val = item$max, 
    prefix = item$prefix
  )
}

# ---- Handle occurred_time and report_time ----

# Function to convert hhmm integer to minutes since midnight
hhmm_to_minutes <- function(x) {
  h <- x %/% 100
  m <- x %% 100
  h * 60 + m
}

# Insert sine/cosine for occurred_time right after occurred_time
ctiii <- ctiii %>%
  mutate(occurred_time_minutes = hhmm_to_minutes(occurred_time))
ctiii <- add_cyclic_features(ctiii, "occurred_time", 1440, "occurred_time")

# Insert sine/cosine for report_time right after report_time
ctiii <- ctiii %>%
  mutate(report_time_minutes = hhmm_to_minutes(report_time))
ctiii <- add_cyclic_features(ctiii, "report_time", 1440, "report_time")

# Remove only the *_minutes helper columns and all the original cyclic columns
cols_to_remove <- c(
  "occurred_date_time_month",
  "occurred_date_time_day_of_week",
  "report_date_time_month",
  "report_date_time_day_of_week",
  "occurred_date_time_week_of_year",
  "occurred_date_time_day",
  "occurred_date_time_hour",
  "occurred_date_time_minute",
  "report_date_time_week_of_year",
  "report_date_time_day",
  "report_date_time_hour",
  "report_date_time_minute",
  "occurred_time_minutes",
  "report_time_minutes",
  "report_time",
  "occurred_time",
  "clearance_date",
  "occurred_date_time",
  "occurred_date",
  "report_date_time",
  "report_date"
)
# NOTE: We do NOT remove occurred_time or report_time here, so the sine/cosine columns appear right next to the originals

ctiii <- ctiii %>%
  select(-all_of(cols_to_remove))
```

## Visualize this data.
```{r,warning=FALSE,message=FALSE}
skim(ctiii)
```
## Save the file
```{r,warning=FALSE,message=FALSE}
#write_csv(ctiii,"./data/crime_test_cleaned.csv")
```

```{r,warning=FALSE,message=FALSE}

```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

