---
title: "VI_"
author: "Sai"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,warning=FALSE,message=FALSE}
library(tidyverse)
library(skimr)
library(ranger)
library(ggplot2)
library(ranger)
```

```{r,warning=FALSE,message=FALSE}
crime <- read_csv("./data/crime_sample.csv")
crime
```
```{r,warning=FALSE,message=FALSE}
crime <- crime %>%
  mutate(
    highest_offense_description = as.factor(highest_offense_description),
    highest_offense_code           = as.factor(highest_offense_code),
    family_violence                = as.factor(family_violence),
    occurred_date_time_month       = as.ordered(occurred_date_time_month),
    occurred_date_time_day_of_week = as.ordered(occurred_date_time_day_of_week),
    location_type                  = as.factor(location_type),
    apd_sector                     = as.factor(apd_sector),
    apd_district                   = as.factor(apd_district)
  )

crime
```


```{r,warning=FALSE,message=FALSE}
rf_data <- crime %>%
  select(-occurred_date_time, -occurred_date, 
         -report_date_time,   -report_date,
         -clearance_date) %>%
  mutate(family_violence = factor(family_violence)) %>% mutate(clearance_status = factor(clearance_status))

rf_data
```
```{r,warning=FALSE,message=FALSE}
set.seed(1906525)

# 1. compute the overall fraction we need
frac <- 50e3 / nrow(rf_data)

# 2. do a proportional (stratified) draw within each clearance_status
sampled <- rf_data %>%
  group_by(clearance_status) %>%
  slice_sample(prop = frac) %>%
  ungroup() %>%
  # 3. in case of rounding you might get ≠50k, so force exactly 50k
  slice_sample(n = 50e3)

sampled
```

# Variable Importance Plot
```{r,warning=FALSE,message=FALSE}
# 1. Fit a ranger with permutation importance
library(vip)
library(tibble)
library(dplyr)
library(ggplot2)

set.seed(1906525)
rf_mod_perm <- ranger(
  formula      = clearance_status ~ .,
  data         = sampled,
  importance   = "permutation",
  num.trees    = 200,               
  write.forest = TRUE,              # needed for OOB permutations
  num.threads  = parallel::detectCores()
)

# 2. Extract the top 10 importances into a tibble
imp_tibble <- rf_mod_perm$variable.importance %>%
  enframe(name = "Variable", value = "Importance") %>%
  arrange(desc(Importance)) %>%
  slice_head(n = 10)

# View the tibble
print(imp_tibble)
#> # A tibble: 10 × 2
#>    Variable           Importance
#>    <chr>                   <dbl>
#>  1 some_top_feature        1.23 
#>  2 next_feature            0.87 
#>  …                       …     

# 3a. Plot with vip (drop-in for your existing code)
vip(
  rf_mod_perm,
  num_features = 10,
  geom         = "col",
  aesthetics   = list(fill = "steelblue")
) +
  coord_flip() +
  labs(
    title = "Top 10 Variable Importances (Permutation)",
    x     = NULL,
    y     = "Importance"
  ) +
  theme_minimal()

# 3b. Alternative: ggplot2 using the tibble you just made
imp_tibble %>%
  ggplot(aes(x = reorder(Variable, Importance), y = Importance)) +
  geom_col(fill = "red") +
  coord_flip() +
  labs(
    title = "Top 10 Variable Importances (Permutation)",
    x     = NULL,
    y     = "Importance"
  ) +
  theme_minimal()
```

```{r,warning=FALSE,message=FALSE}

```

```{r,warning=FALSE,message=FALSE}

```

```{r,warning=FALSE,message=FALSE}

```

```{r,warning=FALSE,message=FALSE}

```

```{r,warning=FALSE,message=FALSE}

```

```{r,warning=FALSE,message=FALSE}

```

```{r,warning=FALSE,message=FALSE}

```

```{r,warning=FALSE,message=FALSE}

```

```{r,warning=FALSE,message=FALSE}

```

```{r,warning=FALSE,message=FALSE}

```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```